import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#172033',
  },
  navigatorContent: {
    backgroundColor: '#172033',
  },
  navigatorHeader: {
    backgroundColor: '#172033',
  },
  navigatorTitle: {
    fontWeight: '800',
  },
  container: {
    flex: 1,
    padding: 16,
  },
  scrollContent: {
    gap: 18,
    paddingBottom: 32,
  },
  header: {
    marginBottom: 28,
    marginTop: 24,
  },
  eyebrow: {
    color: '#0284c7',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 10,
  },
  title: {
    color: '#f8fafc',
    fontSize: 34,
    fontWeight: '800',
    lineHeight: 40,
  },
  screenTitle: {
    color: '#f8fafc',
    fontSize: 30,
    fontWeight: '800',
    marginTop: 24,
  },
  description: {
    color: '#cbd5e1',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 12,
  },
  panel: {
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    gap: 18,
    padding: 20,
  },
  label: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#ffffff',
    borderColor: '#cbd5e1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#0f172a',
    fontSize: 16,
    marginTop: 8,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  row: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  column: {
    alignItems: 'stretch',
    gap: 12,
    justifyContent: 'center',
  },
  layoutToggleRow: {
    alignItems: 'center',
    backgroundColor: '#e2e8f0',
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
  },
  count: {
    color: '#0f172a',
    fontSize: 38,
    fontWeight: '800',
    marginTop: 2,
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#2563eb',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    minWidth: 88,
    paddingHorizontal: 16,
  },
  buttonPressed: {
    opacity: 0.72,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  switchRow: {
    alignItems: 'center',
    borderTopColor: '#e2e8f0',
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 18,
  },
  switchCopy: {
    flex: 1,
    paddingRight: 16,
  },
  helper: {
    color: '#64748b',
    fontSize: 15,
    marginTop: 4,
  },
  navGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  listPanel: {
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    flex: 1,
    marginTop: 20,
    overflow: 'hidden',
  },
  centerState: {
    alignItems: 'center',
    flex: 1,
    gap: 14,
    justifyContent: 'center',
    padding: 24,
  },
  errorText: {
    color: '#dc2626',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  postItem: {
    padding: 18,
  },
  postPressed: {
    backgroundColor: '#e0f2fe',
  },
  postTitle: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
    textTransform: 'capitalize',
  },
  postBody: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  separator: {
    backgroundColor: '#e2e8f0',
    height: 1,
  },
  detailTitle: {
    color: '#0f172a',
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 30,
    textTransform: 'capitalize',
  },
  detailBody: {
    color: '#334155',
    fontSize: 17,
    lineHeight: 26,
  },
  gestureStage: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    flex: 1,
    justifyContent: 'center',
    marginTop: 20,
    overflow: 'hidden',
  },
  gestureCard: {
    alignItems: 'center',
    backgroundColor: '#0f766e',
    borderRadius: 8,
    height: 150,
    justifyContent: 'center',
    width: 190,
  },
  gestureTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '800',
  },
  gestureHint: {
    color: '#ccfbf1',
    fontSize: 15,
    marginTop: 8,
  },
  animationStage: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    flex: 1,
    gap: 24,
    justifyContent: 'center',
    marginTop: 20,
    padding: 24,
  },
  animatedBlock: {
    alignItems: 'center',
    backgroundColor: '#f97316',
    borderRadius: 8,
    height: 112,
    justifyContent: 'center',
  },
  animatedText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  deviceSection: {
    backgroundColor: '#f8fafc',
    borderRadius: 8,
    gap: 12,
    padding: 16,
  },
  sectionTitle: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  cameraFrame: {
    backgroundColor: '#0f172a',
    borderRadius: 8,
    height: 260,
    overflow: 'hidden',
  },
  cameraPreview: {
    flex: 1,
  },
  cameraPlaceholder: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 18,
  },
  placeholderText: {
    color: '#cbd5e1',
    fontSize: 15,
    textAlign: 'center',
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  previewImage: {
    backgroundColor: '#e2e8f0',
    borderRadius: 8,
    height: 180,
    width: '100%',
  },
  resultText: {
    color: '#334155',
    fontSize: 15,
    lineHeight: 22,
  },
  messageBox: {
    backgroundColor: '#e0f2fe',
    borderRadius: 8,
    padding: 14,
  },
  messageText: {
    color: '#075985',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
  },
  tokenBox: {
    backgroundColor: '#e2e8f0',
    borderRadius: 8,
    padding: 12,
  },
  tokenText: {
    color: '#0f172a',
    fontSize: 13,
    lineHeight: 20,
  },
  codeText: {
    color: '#0f172a',
    fontFamily: 'Courier',
    fontSize: 12,
    lineHeight: 18,
  },
});
